# Koyeb Configuration
# Documentation: https://www.koyeb.com/docs/reference/koyeb-yaml

name: pkl-dev-app
services:
  - name: pkl-web
    type: web
    image: null
    git:
      repository: github.com/danu-dev/pkl-dev
      branch: main
      build_command: null
      run_command: null
    env:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: sqlite
    ports:
      - port: 8000
        path: /
        protocol: http
    scalings:
      min: 1
      max: 1
    instance_type: free
    regions:
      - sin
