services:
  - type: web
    name: sipkl-app
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: Dockerfile
    envVars:
      - key: APP_NAME
        value: SIPKL
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: "false"
      - key: DB_CONNECTION
        value: sqlite
      - key: SESSION_DRIVER
        value: database
      - key: FILESYSTEM_DISK
        value: public
      - key: LOG_CHANNEL
        value: stderr
      - key: PORT
        value: 8000
